# Generated by Django 5.1.1 on 2024-10-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='imagem',
        ),
    ]
